[package]
name = "i3switch"
version = "0.0.0" # This is a placeholder version
edition = "2024"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
serde_json = "1.0"
log = "0.4"
simplelog = "0.12"

[dev-dependencies]
ctor = "0.3"
