name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install i3-wm
      run: sudo apt install -y i3-wm
    - name: Install docopt
      run: sudo apt install -y libdocopt0 libdocopt-dev
    - name: Install nlohmann JSON
      run: sudo apt install -y nlohmann-json3-dev
    - name: Run CMake
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
    - name: Build with Make
      run: make -C build
