name: Rust CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install cargo
      run: sudo apt install -y cargo
    - name: cpp build
      run: ./build.sh rust
